#ifndef SD_ANIMATION_EXPORT_HPP
#define SD_ANIMATION_EXPORT_HPP

#include "Utility/Config.hpp"

#if defined(SD_ANIMATION_EXPORT)
#define SD_ANIMATION_API SD_API_EXPORT
#define ENTT_API_EXPORT
#elif defined(SD_ANIMATION_IMPORT)
#define SD_ANIMATION_API SD_API_IMPORT
#define ENTT_API_EXPORT
#else
#define SD_ANIMATION_API
#endif

#endif // !SD_ANIMATION_EXPORT_HPP
